name: Test

on:
  pull_request:
  push:
    branches: [ main, 'releases/**' ]
  release:
    types: [ published ]

jobs:

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Required Tools
      uses: ./.github/workflows/setup-tools
    - name: Test
      run: dotnet test test/DeviceRunners.VisualRunners.Tests --configuration Release /bl:./artifacts/logs/msbuild-test.binlog
    - name: Upload Logs
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: Logs - Windows
        path: ./artifacts/logs

  macos:
    name: macOS
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Required Tools
      uses: ./.github/workflows/setup-tools
    - name: Test
      run: dotnet test test/DeviceRunners.VisualRunners.Tests --configuration Release /bl:./artifacts/logs/msbuild-test.binlog
    - name: Upload Logs
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: Logs - macOS
        path: ./artifacts/logs
