name: Test

on:
  pull_request:
  push:
    branches: [ main, 'releases/**' ]
  release:
    types: [ published ]

jobs:

  ios:
    name: iOS
    runs-on: macos-13
    env:
      TEST_TARGET_FRAMEWORK: net8.0-ios
      TEST_RUNTIME_IDENTIFIER: iossimulator-x64_16.4
      TEST_CONFIGURATION: Debug
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Required Tools
      uses: ./.github/workflows/setup-tools
    - name: Publish App
      run: |
        dotnet build sample/SampleMauiApp/SampleMauiApp.csproj \
          -f ${{ env.TEST_TARGET_FRAMEWORK }} \
          -r ${{ env.TEST_RUNTIME_IDENTIFIER }} \
          -c ${{ env.TEST_CONFIGURATION }} \
          /bl:./artifacts/logs/msbuild-publish.binlog
    - name: Run Tests
      run: |
        dotnet xharness apple test \
          --target ios-simulator-64 \
          --app sample/SampleMauiApp/bin/${{ env.TEST_CONFIGURATION }}/${{ env.TEST_TARGET_FRAMEWORK }}/${{ env.TEST_RUNTIME_IDENTIFIER }}/SampleMauiApp.app \
          --output-directory artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: Test Results - iOS
        path: ./artifacts


  maccatalyst:
    name: Mac Catalyst
    runs-on: macos-13
    env:
      TEST_TARGET_FRAMEWORK: net8.0-maccatalyst
      TEST_RUNTIME_IDENTIFIER: maccatalyst-x64
      TEST_CONFIGURATION: Debug
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Required Tools
      uses: ./.github/workflows/setup-tools
    - name: Publish App
      run: |
        dotnet build sample/SampleMauiApp/SampleMauiApp.csproj \
          -f ${{ env.TEST_TARGET_FRAMEWORK }} \
          -r ${{ env.TEST_RUNTIME_IDENTIFIER }} \
          -c ${{ env.TEST_CONFIGURATION }} \
          /bl:./artifacts/logs/msbuild-publish.binlog
    - name: Run Tests
      run: |
        dotnet xharness apple test \
          --target maccatalyst \
          --app sample/SampleMauiApp/bin/${{ env.TEST_CONFIGURATION }}/${{ env.TEST_TARGET_FRAMEWORK }}/${{ env.TEST_RUNTIME_IDENTIFIER }}/SampleMauiApp.app \
          --output-directory artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: Test Results - Mac Catalyst
        path: ./artifacts


  windows:
    name: Windows
    runs-on: windows-latest
    env:
      TEST_TARGET_FRAMEWORK: net8.0-windows10.0.19041.0
      TEST_RUNTIME_IDENTIFIER: win10-x64
      TEST_CONFIGURATION: Release
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Required Tools
      uses: ./.github/workflows/setup-tools
    - name: Publish App
      run: |
        $fingerprint = ./scripts/New-Certificate.ps1 -Project sample/SampleMauiApp/SampleMauiApp.csproj
        dotnet publish sample/SampleMauiApp/SampleMauiApp.csproj `
          -f ${{ env.TEST_TARGET_FRAMEWORK }} `
          -c ${{ env.TEST_CONFIGURATION }} `
          -p:AppxPackageSigningEnabled=true `
          -p:PackageCertificateThumbprint=$fingerprint `
          -p:PackageCertificateKeyFile="" `
          /bl:./artifacts/logs/msbuild-publish.binlog
        ./scripts/Remove-Certificate.ps1 -CertificateFingerprint $fingerprint
    - name: Run Tests
      run: |
        $msix = Get-ChildItem "sample/SampleMauiApp/bin/${{ env.TEST_CONFIGURATION }}/${{ env.TEST_TARGET_FRAMEWORK }}/${{ env.TEST_RUNTIME_IDENTIFIER }}/AppPackages/*_Test/*.msix"
        ./scripts/Start-Tests.ps1 `
          -App $msix `
          -OutputDirectory artifacts
      shell: powershell
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: Test Results - Windows
        path: ./artifacts


  # android:
  #   name: Android
  #   runs-on: macos-13
  #   env:
  #     TEST_TARGET_FRAMEWORK: net8.0-android
  #     TEST_RUNTIME_IDENTIFIER: android-x64
  #     TEST_CONFIGURATION: Release
  #     TEST_EMULATOR_IMAGE: system-images;android-34;google_apis;x86_64
  #     TEST_EMULATOR_DEVICE: pixel_5
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Setup Required Tools
  #     uses: ./.github/workflows/setup-tools
  #   - name: Install Emulator Image
  #     run: dotnet android sdk install --package "${{ env.TEST_EMULATOR_IMAGE }}"
  #   - name: Create the Emulator
  #     run: dotnet android avd create --name TestRunnerEmulator --sdk "${{ env.TEST_EMULATOR_IMAGE }}" --device "${{ env.TEST_EMULATOR_DEVICE }}"
  #   - name: Boot the Emulator
  #     run: dotnet android avd start --name TestRunnerEmulator --wait-boot
  #   - name: Publish App
  #     run: |
  #       dotnet publish sample/SampleMauiApp/SampleMauiApp.csproj \
  #         -f ${{ env.TEST_TARGET_FRAMEWORK }} \
  #         -r ${{ env.TEST_RUNTIME_IDENTIFIER }} \
  #         -c ${{ env.TEST_CONFIGURATION }} \
  #         /bl:./artifacts/logs/msbuild-publish.binlog
  #   - name: Run Tests
  #     run: |
  #       xharness android test \
  #         --package-name com.companyname.samplemauiapp \
  #         --instrumentation devicerunners.xharness.maui.XHarnessInstrumentation \
  #         --app sample/SampleMauiApp/bin/${{ env.TEST_CONFIGURATION }}/${{ env.TEST_TARGET_FRAMEWORK }}/${{ env.TEST_RUNTIME_IDENTIFIER }}/publish/com.companyname.samplemauiapp-Signed.apk
  #         --output-directory artifacts
  #   - name: Shutdown the Emulator
  #     run: dotnet xharness android adb -- emu kill
  #   - name: Upload Artifacts
  #     uses: actions/upload-artifact@v1
  #     if: ${{ always() }}
  #     with:
  #       name: Test Results - Android
  #       path: ./artifacts
